<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pais;
use App\Models\Estado;
use App\Models\Ciudad;

class UbicacionSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedPaises();
        $this->seedEstadosArgentina();
        $this->seedCiudadesArgentina();
    }

    private function seedPaises(): void
    {
        $paises = [
            ['nombre' => 'Afganistán',                             'nombre_ingles' => 'Afghanistan',                              'iso2' => 'AF', 'iso3' => 'AFG', 'iso_numerico' => '004'],
            ['nombre' => 'Albania',                                'nombre_ingles' => 'Albania',                                  'iso2' => 'AL', 'iso3' => 'ALB', 'iso_numerico' => '008'],
            ['nombre' => 'Alemania',                               'nombre_ingles' => 'Germany',                                  'iso2' => 'DE', 'iso3' => 'DEU', 'iso_numerico' => '276'],
            ['nombre' => 'Andorra',                                'nombre_ingles' => 'Andorra',                                  'iso2' => 'AD', 'iso3' => 'AND', 'iso_numerico' => '020'],
            ['nombre' => 'Angola',                                 'nombre_ingles' => 'Angola',                                   'iso2' => 'AO', 'iso3' => 'AGO', 'iso_numerico' => '024'],
            ['nombre' => 'Antigua y Barbuda',                      'nombre_ingles' => 'Antigua and Barbuda',                      'iso2' => 'AG', 'iso3' => 'ATG', 'iso_numerico' => '028'],
            ['nombre' => 'Arabia Saudita',                         'nombre_ingles' => 'Saudi Arabia',                             'iso2' => 'SA', 'iso3' => 'SAU', 'iso_numerico' => '682'],
            ['nombre' => 'Argelia',                                'nombre_ingles' => 'Algeria',                                  'iso2' => 'DZ', 'iso3' => 'DZA', 'iso_numerico' => '012'],
            ['nombre' => 'Argentina',                              'nombre_ingles' => 'Argentina',                                'iso2' => 'AR', 'iso3' => 'ARG', 'iso_numerico' => '032'],
            ['nombre' => 'Armenia',                                'nombre_ingles' => 'Armenia',                                  'iso2' => 'AM', 'iso3' => 'ARM', 'iso_numerico' => '051'],
            ['nombre' => 'Australia',                              'nombre_ingles' => 'Australia',                                'iso2' => 'AU', 'iso3' => 'AUS', 'iso_numerico' => '036'],
            ['nombre' => 'Austria',                                'nombre_ingles' => 'Austria',                                  'iso2' => 'AT', 'iso3' => 'AUT', 'iso_numerico' => '040'],
            ['nombre' => 'Azerbaiyán',                             'nombre_ingles' => 'Azerbaijan',                               'iso2' => 'AZ', 'iso3' => 'AZE', 'iso_numerico' => '031'],
            ['nombre' => 'Bahamas',                                'nombre_ingles' => 'Bahamas',                                  'iso2' => 'BS', 'iso3' => 'BHS', 'iso_numerico' => '044'],
            ['nombre' => 'Bangladés',                              'nombre_ingles' => 'Bangladesh',                               'iso2' => 'BD', 'iso3' => 'BGD', 'iso_numerico' => '050'],
            ['nombre' => 'Barbados',                               'nombre_ingles' => 'Barbados',                                 'iso2' => 'BB', 'iso3' => 'BRB', 'iso_numerico' => '052'],
            ['nombre' => 'Baréin',                                 'nombre_ingles' => 'Bahrain',                                  'iso2' => 'BH', 'iso3' => 'BHR', 'iso_numerico' => '048'],
            ['nombre' => 'Bélgica',                                'nombre_ingles' => 'Belgium',                                  'iso2' => 'BE', 'iso3' => 'BEL', 'iso_numerico' => '056'],
            ['nombre' => 'Belice',                                 'nombre_ingles' => 'Belize',                                   'iso2' => 'BZ', 'iso3' => 'BLZ', 'iso_numerico' => '084'],
            ['nombre' => 'Benín',                                  'nombre_ingles' => 'Benin',                                    'iso2' => 'BJ', 'iso3' => 'BEN', 'iso_numerico' => '204'],
            ['nombre' => 'Bielorrusia',                            'nombre_ingles' => 'Belarus',                                  'iso2' => 'BY', 'iso3' => 'BLR', 'iso_numerico' => '112'],
            ['nombre' => 'Birmania',                               'nombre_ingles' => 'Myanmar',                                  'iso2' => 'MM', 'iso3' => 'MMR', 'iso_numerico' => '104'],
            ['nombre' => 'Bolivia',                                'nombre_ingles' => 'Bolivia',                                  'iso2' => 'BO', 'iso3' => 'BOL', 'iso_numerico' => '068'],
            ['nombre' => 'Bosnia y Herzegovina',                   'nombre_ingles' => 'Bosnia and Herzegovina',                   'iso2' => 'BA', 'iso3' => 'BIH', 'iso_numerico' => '070'],
            ['nombre' => 'Botsuana',                               'nombre_ingles' => 'Botswana',                                 'iso2' => 'BW', 'iso3' => 'BWA', 'iso_numerico' => '072'],
            ['nombre' => 'Brasil',                                 'nombre_ingles' => 'Brazil',                                   'iso2' => 'BR', 'iso3' => 'BRA', 'iso_numerico' => '076'],
            ['nombre' => 'Brunéi',                                 'nombre_ingles' => 'Brunei',                                   'iso2' => 'BN', 'iso3' => 'BRN', 'iso_numerico' => '096'],
            ['nombre' => 'Bulgaria',                               'nombre_ingles' => 'Bulgaria',                                 'iso2' => 'BG', 'iso3' => 'BGR', 'iso_numerico' => '100'],
            ['nombre' => 'Burkina Faso',                           'nombre_ingles' => 'Burkina Faso',                             'iso2' => 'BF', 'iso3' => 'BFA', 'iso_numerico' => '854'],
            ['nombre' => 'Burundi',                                'nombre_ingles' => 'Burundi',                                  'iso2' => 'BI', 'iso3' => 'BDI', 'iso_numerico' => '108'],
            ['nombre' => 'Bután',                                  'nombre_ingles' => 'Bhutan',                                   'iso2' => 'BT', 'iso3' => 'BTN', 'iso_numerico' => '064'],
            ['nombre' => 'Cabo Verde',                             'nombre_ingles' => 'Cape Verde',                               'iso2' => 'CV', 'iso3' => 'CPV', 'iso_numerico' => '132'],
            ['nombre' => 'Camboya',                                'nombre_ingles' => 'Cambodia',                                 'iso2' => 'KH', 'iso3' => 'KHM', 'iso_numerico' => '116'],
            ['nombre' => 'Camerún',                                'nombre_ingles' => 'Cameroon',                                 'iso2' => 'CM', 'iso3' => 'CMR', 'iso_numerico' => '120'],
            ['nombre' => 'Canadá',                                 'nombre_ingles' => 'Canada',                                   'iso2' => 'CA', 'iso3' => 'CAN', 'iso_numerico' => '124'],
            ['nombre' => 'Catar',                                  'nombre_ingles' => 'Qatar',                                    'iso2' => 'QA', 'iso3' => 'QAT', 'iso_numerico' => '634'],
            ['nombre' => 'Chad',                                   'nombre_ingles' => 'Chad',                                     'iso2' => 'TD', 'iso3' => 'TCD', 'iso_numerico' => '148'],
            ['nombre' => 'Chile',                                  'nombre_ingles' => 'Chile',                                    'iso2' => 'CL', 'iso3' => 'CHL', 'iso_numerico' => '152'],
            ['nombre' => 'China',                                  'nombre_ingles' => 'China',                                    'iso2' => 'CN', 'iso3' => 'CHN', 'iso_numerico' => '156'],
            ['nombre' => 'Chipre',                                 'nombre_ingles' => 'Cyprus',                                   'iso2' => 'CY', 'iso3' => 'CYP', 'iso_numerico' => '196'],
            ['nombre' => 'Ciudad del Vaticano',                    'nombre_ingles' => 'Vatican City',                             'iso2' => 'VA', 'iso3' => 'VAT', 'iso_numerico' => '336'],
            ['nombre' => 'Colombia',                               'nombre_ingles' => 'Colombia',                                 'iso2' => 'CO', 'iso3' => 'COL', 'iso_numerico' => '170'],
            ['nombre' => 'Comoras',                                'nombre_ingles' => 'Comoros',                                  'iso2' => 'KM', 'iso3' => 'COM', 'iso_numerico' => '174'],
            ['nombre' => 'Congo',                                  'nombre_ingles' => 'Republic of the Congo',                    'iso2' => 'CG', 'iso3' => 'COG', 'iso_numerico' => '178'],
            ['nombre' => 'Corea del Norte',                        'nombre_ingles' => 'North Korea',                              'iso2' => 'KP', 'iso3' => 'PRK', 'iso_numerico' => '408'],
            ['nombre' => 'Corea del Sur',                         'nombre_ingles' => 'South Korea',                              'iso2' => 'KR', 'iso3' => 'KOR', 'iso_numerico' => '410'],
            ['nombre' => 'Costa de Marfil',                        'nombre_ingles' => "Côte d'Ivoire",                            'iso2' => 'CI', 'iso3' => 'CIV', 'iso_numerico' => '384'],
            ['nombre' => 'Costa Rica',                             'nombre_ingles' => 'Costa Rica',                               'iso2' => 'CR', 'iso3' => 'CRI', 'iso_numerico' => '188'],
            ['nombre' => 'Croacia',                                'nombre_ingles' => 'Croatia',                                  'iso2' => 'HR', 'iso3' => 'HRV', 'iso_numerico' => '191'],
            ['nombre' => 'Cuba',                                   'nombre_ingles' => 'Cuba',                                     'iso2' => 'CU', 'iso3' => 'CUB', 'iso_numerico' => '192'],
            ['nombre' => 'Dinamarca',                              'nombre_ingles' => 'Denmark',                                  'iso2' => 'DK', 'iso3' => 'DNK', 'iso_numerico' => '208'],
            ['nombre' => 'Dominica',                               'nombre_ingles' => 'Dominica',                                 'iso2' => 'DM', 'iso3' => 'DMA', 'iso_numerico' => '212'],
            ['nombre' => 'Ecuador',                                'nombre_ingles' => 'Ecuador',                                  'iso2' => 'EC', 'iso3' => 'ECU', 'iso_numerico' => '218'],
            ['nombre' => 'Egipto',                                 'nombre_ingles' => 'Egypt',                                    'iso2' => 'EG', 'iso3' => 'EGY', 'iso_numerico' => '818'],
            ['nombre' => 'El Salvador',                            'nombre_ingles' => 'El Salvador',                              'iso2' => 'SV', 'iso3' => 'SLV', 'iso_numerico' => '222'],
            ['nombre' => 'Emiratos Árabes Unidos',                 'nombre_ingles' => 'United Arab Emirates',                     'iso2' => 'AE', 'iso3' => 'ARE', 'iso_numerico' => '784'],
            ['nombre' => 'Eritrea',                                'nombre_ingles' => 'Eritrea',                                  'iso2' => 'ER', 'iso3' => 'ERI', 'iso_numerico' => '232'],
            ['nombre' => 'Eslovaquia',                             'nombre_ingles' => 'Slovakia',                                 'iso2' => 'SK', 'iso3' => 'SVK', 'iso_numerico' => '703'],
            ['nombre' => 'Eslovenia',                              'nombre_ingles' => 'Slovenia',                                 'iso2' => 'SI', 'iso3' => 'SVN', 'iso_numerico' => '705'],
            ['nombre' => 'España',                                 'nombre_ingles' => 'Spain',                                    'iso2' => 'ES', 'iso3' => 'ESP', 'iso_numerico' => '724'],
            ['nombre' => 'Estados Unidos',                         'nombre_ingles' => 'United States',                            'iso2' => 'US', 'iso3' => 'USA', 'iso_numerico' => '840'],
            ['nombre' => 'Estonia',                                'nombre_ingles' => 'Estonia',                                  'iso2' => 'EE', 'iso3' => 'EST', 'iso_numerico' => '233'],
            ['nombre' => 'Etiopía',                                'nombre_ingles' => 'Ethiopia',                                 'iso2' => 'ET', 'iso3' => 'ETH', 'iso_numerico' => '231'],
            ['nombre' => 'Filipinas',                              'nombre_ingles' => 'Philippines',                              'iso2' => 'PH', 'iso3' => 'PHL', 'iso_numerico' => '608'],
            ['nombre' => 'Finlandia',                              'nombre_ingles' => 'Finland',                                  'iso2' => 'FI', 'iso3' => 'FIN', 'iso_numerico' => '246'],
            ['nombre' => 'Fiyi',                                   'nombre_ingles' => 'Fiji',                                     'iso2' => 'FJ', 'iso3' => 'FJI', 'iso_numerico' => '242'],
            ['nombre' => 'Francia',                                'nombre_ingles' => 'France',                                   'iso2' => 'FR', 'iso3' => 'FRA', 'iso_numerico' => '250'],
            ['nombre' => 'Gabón',                                  'nombre_ingles' => 'Gabon',                                    'iso2' => 'GA', 'iso3' => 'GAB', 'iso_numerico' => '266'],
            ['nombre' => 'Gambia',                                 'nombre_ingles' => 'Gambia',                                   'iso2' => 'GM', 'iso3' => 'GMB', 'iso_numerico' => '270'],
            ['nombre' => 'Georgia',                                'nombre_ingles' => 'Georgia',                                  'iso2' => 'GE', 'iso3' => 'GEO', 'iso_numerico' => '268'],
            ['nombre' => 'Ghana',                                  'nombre_ingles' => 'Ghana',                                    'iso2' => 'GH', 'iso3' => 'GHA', 'iso_numerico' => '288'],
            ['nombre' => 'Granada',                                'nombre_ingles' => 'Grenada',                                  'iso2' => 'GD', 'iso3' => 'GRD', 'iso_numerico' => '308'],
            ['nombre' => 'Grecia',                                 'nombre_ingles' => 'Greece',                                   'iso2' => 'GR', 'iso3' => 'GRC', 'iso_numerico' => '300'],
            ['nombre' => 'Guatemala',                              'nombre_ingles' => 'Guatemala',                                'iso2' => 'GT', 'iso3' => 'GTM', 'iso_numerico' => '320'],
            ['nombre' => 'Guinea',                                 'nombre_ingles' => 'Guinea',                                   'iso2' => 'GN', 'iso3' => 'GIN', 'iso_numerico' => '324'],
            ['nombre' => 'Guinea Ecuatorial',                      'nombre_ingles' => 'Equatorial Guinea',                        'iso2' => 'GQ', 'iso3' => 'GNQ', 'iso_numerico' => '226'],
            ['nombre' => 'Guinea-Bisáu',                           'nombre_ingles' => 'Guinea-Bissau',                            'iso2' => 'GW', 'iso3' => 'GNB', 'iso_numerico' => '624'],
            ['nombre' => 'Guyana',                                 'nombre_ingles' => 'Guyana',                                   'iso2' => 'GY', 'iso3' => 'GUY', 'iso_numerico' => '328'],
            ['nombre' => 'Haití',                                  'nombre_ingles' => 'Haiti',                                    'iso2' => 'HT', 'iso3' => 'HTI', 'iso_numerico' => '332'],
            ['nombre' => 'Honduras',                               'nombre_ingles' => 'Honduras',                                 'iso2' => 'HN', 'iso3' => 'HND', 'iso_numerico' => '340'],
            ['nombre' => 'Hungría',                                'nombre_ingles' => 'Hungary',                                  'iso2' => 'HU', 'iso3' => 'HUN', 'iso_numerico' => '348'],
            ['nombre' => 'India',                                  'nombre_ingles' => 'India',                                    'iso2' => 'IN', 'iso3' => 'IND', 'iso_numerico' => '356'],
            ['nombre' => 'Indonesia',                              'nombre_ingles' => 'Indonesia',                                'iso2' => 'ID', 'iso3' => 'IDN', 'iso_numerico' => '360'],
            ['nombre' => 'Irak',                                   'nombre_ingles' => 'Iraq',                                     'iso2' => 'IQ', 'iso3' => 'IRQ', 'iso_numerico' => '368'],
            ['nombre' => 'Irán',                                   'nombre_ingles' => 'Iran',                                     'iso2' => 'IR', 'iso3' => 'IRN', 'iso_numerico' => '364'],
            ['nombre' => 'Irlanda',                                'nombre_ingles' => 'Ireland',                                  'iso2' => 'IE', 'iso3' => 'IRL', 'iso_numerico' => '372'],
            ['nombre' => 'Islandia',                               'nombre_ingles' => 'Iceland',                                  'iso2' => 'IS', 'iso3' => 'ISL', 'iso_numerico' => '352'],
            ['nombre' => 'Islas Marshall',                         'nombre_ingles' => 'Marshall Islands',                         'iso2' => 'MH', 'iso3' => 'MHL', 'iso_numerico' => '584'],
            ['nombre' => 'Islas Salomón',                          'nombre_ingles' => 'Solomon Islands',                          'iso2' => 'SB', 'iso3' => 'SLB', 'iso_numerico' => '090'],
            ['nombre' => 'Israel',                                 'nombre_ingles' => 'Israel',                                   'iso2' => 'IL', 'iso3' => 'ISR', 'iso_numerico' => '376'],
            ['nombre' => 'Italia',                                 'nombre_ingles' => 'Italy',                                    'iso2' => 'IT', 'iso3' => 'ITA', 'iso_numerico' => '380'],
            ['nombre' => 'Jamaica',                                'nombre_ingles' => 'Jamaica',                                  'iso2' => 'JM', 'iso3' => 'JAM', 'iso_numerico' => '388'],
            ['nombre' => 'Japón',                                  'nombre_ingles' => 'Japan',                                    'iso2' => 'JP', 'iso3' => 'JPN', 'iso_numerico' => '392'],
            ['nombre' => 'Jordania',                               'nombre_ingles' => 'Jordan',                                   'iso2' => 'JO', 'iso3' => 'JOR', 'iso_numerico' => '400'],
            ['nombre' => 'Kazajistán',                             'nombre_ingles' => 'Kazakhstan',                               'iso2' => 'KZ', 'iso3' => 'KAZ', 'iso_numerico' => '398'],
            ['nombre' => 'Kenia',                                  'nombre_ingles' => 'Kenya',                                    'iso2' => 'KE', 'iso3' => 'KEN', 'iso_numerico' => '404'],
            ['nombre' => 'Kirguistán',                             'nombre_ingles' => 'Kyrgyzstan',                               'iso2' => 'KG', 'iso3' => 'KGZ', 'iso_numerico' => '417'],
            ['nombre' => 'Kiribati',                               'nombre_ingles' => 'Kiribati',                                 'iso2' => 'KI', 'iso3' => 'KIR', 'iso_numerico' => '296'],
            ['nombre' => 'Kuwait',                                 'nombre_ingles' => 'Kuwait',                                   'iso2' => 'KW', 'iso3' => 'KWT', 'iso_numerico' => '414'],
            ['nombre' => 'Laos',                                   'nombre_ingles' => 'Laos',                                     'iso2' => 'LA', 'iso3' => 'LAO', 'iso_numerico' => '418'],
            ['nombre' => 'Lesoto',                                 'nombre_ingles' => 'Lesotho',                                  'iso2' => 'LS', 'iso3' => 'LSO', 'iso_numerico' => '426'],
            ['nombre' => 'Letonia',                                'nombre_ingles' => 'Latvia',                                   'iso2' => 'LV', 'iso3' => 'LVA', 'iso_numerico' => '428'],
            ['nombre' => 'Líbano',                                 'nombre_ingles' => 'Lebanon',                                  'iso2' => 'LB', 'iso3' => 'LBN', 'iso_numerico' => '422'],
            ['nombre' => 'Liberia',                                'nombre_ingles' => 'Liberia',                                  'iso2' => 'LR', 'iso3' => 'LBR', 'iso_numerico' => '430'],
            ['nombre' => 'Libia',                                  'nombre_ingles' => 'Libya',                                    'iso2' => 'LY', 'iso3' => 'LBY', 'iso_numerico' => '434'],
            ['nombre' => 'Liechtenstein',                          'nombre_ingles' => 'Liechtenstein',                            'iso2' => 'LI', 'iso3' => 'LIE', 'iso_numerico' => '438'],
            ['nombre' => 'Lituania',                               'nombre_ingles' => 'Lithuania',                                'iso2' => 'LT', 'iso3' => 'LTU', 'iso_numerico' => '440'],
            ['nombre' => 'Luxemburgo',                             'nombre_ingles' => 'Luxembourg',                               'iso2' => 'LU', 'iso3' => 'LUX', 'iso_numerico' => '442'],
            ['nombre' => 'Madagascar',                             'nombre_ingles' => 'Madagascar',                               'iso2' => 'MG', 'iso3' => 'MDG', 'iso_numerico' => '450'],
            ['nombre' => 'Malasia',                                'nombre_ingles' => 'Malaysia',                                 'iso2' => 'MY', 'iso3' => 'MYS', 'iso_numerico' => '458'],
            ['nombre' => 'Malaui',                                 'nombre_ingles' => 'Malawi',                                   'iso2' => 'MW', 'iso3' => 'MWI', 'iso_numerico' => '454'],
            ['nombre' => 'Maldivas',                               'nombre_ingles' => 'Maldives',                                 'iso2' => 'MV', 'iso3' => 'MDV', 'iso_numerico' => '462'],
            ['nombre' => 'Malí',                                   'nombre_ingles' => 'Mali',                                     'iso2' => 'ML', 'iso3' => 'MLI', 'iso_numerico' => '466'],
            ['nombre' => 'Malta',                                  'nombre_ingles' => 'Malta',                                    'iso2' => 'MT', 'iso3' => 'MLT', 'iso_numerico' => '470'],
            ['nombre' => 'Marruecos',                              'nombre_ingles' => 'Morocco',                                  'iso2' => 'MA', 'iso3' => 'MAR', 'iso_numerico' => '504'],
            ['nombre' => 'Mauricio',                               'nombre_ingles' => 'Mauritius',                                'iso2' => 'MU', 'iso3' => 'MUS', 'iso_numerico' => '480'],
            ['nombre' => 'Mauritania',                             'nombre_ingles' => 'Mauritania',                               'iso2' => 'MR', 'iso3' => 'MRT', 'iso_numerico' => '478'],
            ['nombre' => 'México',                                 'nombre_ingles' => 'Mexico',                                   'iso2' => 'MX', 'iso3' => 'MEX', 'iso_numerico' => '484'],
            ['nombre' => 'Micronesia',                             'nombre_ingles' => 'Micronesia',                               'iso2' => 'FM', 'iso3' => 'FSM', 'iso_numerico' => '583'],
            ['nombre' => 'Moldavia',                               'nombre_ingles' => 'Moldova',                                  'iso2' => 'MD', 'iso3' => 'MDA', 'iso_numerico' => '498'],
            ['nombre' => 'Mónaco',                                 'nombre_ingles' => 'Monaco',                                   'iso2' => 'MC', 'iso3' => 'MCO', 'iso_numerico' => '492'],
            ['nombre' => 'Mongolia',                               'nombre_ingles' => 'Mongolia',                                 'iso2' => 'MN', 'iso3' => 'MNG', 'iso_numerico' => '496'],
            ['nombre' => 'Montenegro',                             'nombre_ingles' => 'Montenegro',                               'iso2' => 'ME', 'iso3' => 'MNE', 'iso_numerico' => '499'],
            ['nombre' => 'Mozambique',                             'nombre_ingles' => 'Mozambique',                               'iso2' => 'MZ', 'iso3' => 'MOZ', 'iso_numerico' => '508'],
            ['nombre' => 'Namibia',                                'nombre_ingles' => 'Namibia',                                  'iso2' => 'NA', 'iso3' => 'NAM', 'iso_numerico' => '516'],
            ['nombre' => 'Nauru',                                  'nombre_ingles' => 'Nauru',                                    'iso2' => 'NR', 'iso3' => 'NRU', 'iso_numerico' => '520'],
            ['nombre' => 'Nepal',                                  'nombre_ingles' => 'Nepal',                                    'iso2' => 'NP', 'iso3' => 'NPL', 'iso_numerico' => '524'],
            ['nombre' => 'Nicaragua',                              'nombre_ingles' => 'Nicaragua',                                'iso2' => 'NI', 'iso3' => 'NIC', 'iso_numerico' => '558'],
            ['nombre' => 'Níger',                                  'nombre_ingles' => 'Niger',                                    'iso2' => 'NE', 'iso3' => 'NER', 'iso_numerico' => '562'],
            ['nombre' => 'Nigeria',                                'nombre_ingles' => 'Nigeria',                                  'iso2' => 'NG', 'iso3' => 'NGA', 'iso_numerico' => '566'],
            ['nombre' => 'Noruega',                                'nombre_ingles' => 'Norway',                                   'iso2' => 'NO', 'iso3' => 'NOR', 'iso_numerico' => '578'],
            ['nombre' => 'Nueva Zelanda',                          'nombre_ingles' => 'New Zealand',                              'iso2' => 'NZ', 'iso3' => 'NZL', 'iso_numerico' => '554'],
            ['nombre' => 'Omán',                                   'nombre_ingles' => 'Oman',                                     'iso2' => 'OM', 'iso3' => 'OMN', 'iso_numerico' => '512'],
            ['nombre' => 'Países Bajos',                           'nombre_ingles' => 'Netherlands',                              'iso2' => 'NL', 'iso3' => 'NLD', 'iso_numerico' => '528'],
            ['nombre' => 'Pakistán',                               'nombre_ingles' => 'Pakistan',                                 'iso2' => 'PK', 'iso3' => 'PAK', 'iso_numerico' => '586'],
            ['nombre' => 'Palaos',                                 'nombre_ingles' => 'Palau',                                    'iso2' => 'PW', 'iso3' => 'PLW', 'iso_numerico' => '585'],
            ['nombre' => 'Palestina',                              'nombre_ingles' => 'Palestine',                                'iso2' => 'PS', 'iso3' => 'PSE', 'iso_numerico' => '275'],
            ['nombre' => 'Panamá',                                 'nombre_ingles' => 'Panama',                                   'iso2' => 'PA', 'iso3' => 'PAN', 'iso_numerico' => '591'],
            ['nombre' => 'Papúa Nueva Guinea',                     'nombre_ingles' => 'Papua New Guinea',                         'iso2' => 'PG', 'iso3' => 'PNG', 'iso_numerico' => '598'],
            ['nombre' => 'Paraguay',                               'nombre_ingles' => 'Paraguay',                                 'iso2' => 'PY', 'iso3' => 'PRY', 'iso_numerico' => '600'],
            ['nombre' => 'Perú',                                   'nombre_ingles' => 'Peru',                                     'iso2' => 'PE', 'iso3' => 'PER', 'iso_numerico' => '604'],
            ['nombre' => 'Polonia',                                'nombre_ingles' => 'Poland',                                   'iso2' => 'PL', 'iso3' => 'POL', 'iso_numerico' => '616'],
            ['nombre' => 'Portugal',                               'nombre_ingles' => 'Portugal',                                 'iso2' => 'PT', 'iso3' => 'PRT', 'iso_numerico' => '620'],
            ['nombre' => 'Reino Unido',                            'nombre_ingles' => 'United Kingdom',                           'iso2' => 'GB', 'iso3' => 'GBR', 'iso_numerico' => '826'],
            ['nombre' => 'República Centroafricana',               'nombre_ingles' => 'Central African Republic',                 'iso2' => 'CF', 'iso3' => 'CAF', 'iso_numerico' => '140'],
            ['nombre' => 'República Checa',                        'nombre_ingles' => 'Czech Republic',                           'iso2' => 'CZ', 'iso3' => 'CZE', 'iso_numerico' => '203'],
            ['nombre' => 'República del Congo',                    'nombre_ingles' => 'Democratic Republic of the Congo',         'iso2' => 'CD', 'iso3' => 'COD', 'iso_numerico' => '180'],
            ['nombre' => 'República Dominicana',                   'nombre_ingles' => 'Dominican Republic',                       'iso2' => 'DO', 'iso3' => 'DOM', 'iso_numerico' => '214'],
            ['nombre' => 'Ruanda',                                 'nombre_ingles' => 'Rwanda',                                   'iso2' => 'RW', 'iso3' => 'RWA', 'iso_numerico' => '646'],
            ['nombre' => 'Rumanía',                                'nombre_ingles' => 'Romania',                                  'iso2' => 'RO', 'iso3' => 'ROU', 'iso_numerico' => '642'],
            ['nombre' => 'Rusia',                                  'nombre_ingles' => 'Russia',                                   'iso2' => 'RU', 'iso3' => 'RUS', 'iso_numerico' => '643'],
            ['nombre' => 'Samoa',                                  'nombre_ingles' => 'Samoa',                                    'iso2' => 'WS', 'iso3' => 'WSM', 'iso_numerico' => '882'],
            ['nombre' => 'San Cristóbal y Nieves',                 'nombre_ingles' => 'Saint Kitts and Nevis',                    'iso2' => 'KN', 'iso3' => 'KNA', 'iso_numerico' => '659'],
            ['nombre' => 'San Marino',                             'nombre_ingles' => 'San Marino',                               'iso2' => 'SM', 'iso3' => 'SMR', 'iso_numerico' => '674'],
            ['nombre' => 'San Vicente y las Granadinas',           'nombre_ingles' => 'Saint Vincent and the Grenadines',         'iso2' => 'VC', 'iso3' => 'VCT', 'iso_numerico' => '670'],
            ['nombre' => 'Santa Lucía',                            'nombre_ingles' => 'Saint Lucia',                              'iso2' => 'LC', 'iso3' => 'LCA', 'iso_numerico' => '662'],
            ['nombre' => 'Santo Tomé y Príncipe',                  'nombre_ingles' => 'São Tomé and Príncipe',                    'iso2' => 'ST', 'iso3' => 'STP', 'iso_numerico' => '678'],
            ['nombre' => 'Senegal',                                'nombre_ingles' => 'Senegal',                                  'iso2' => 'SN', 'iso3' => 'SEN', 'iso_numerico' => '686'],
            ['nombre' => 'Serbia',                                 'nombre_ingles' => 'Serbia',                                   'iso2' => 'RS', 'iso3' => 'SRB', 'iso_numerico' => '688'],
            ['nombre' => 'Seychelles',                             'nombre_ingles' => 'Seychelles',                               'iso2' => 'SC', 'iso3' => 'SYC', 'iso_numerico' => '690'],
            ['nombre' => 'Sierra Leona',                           'nombre_ingles' => 'Sierra Leone',                             'iso2' => 'SL', 'iso3' => 'SLE', 'iso_numerico' => '694'],
            ['nombre' => 'Singapur',                               'nombre_ingles' => 'Singapore',                                'iso2' => 'SG', 'iso3' => 'SGP', 'iso_numerico' => '702'],
            ['nombre' => 'Siria',                                  'nombre_ingles' => 'Syria',                                    'iso2' => 'SY', 'iso3' => 'SYR', 'iso_numerico' => '760'],
            ['nombre' => 'Somalia',                                'nombre_ingles' => 'Somalia',                                  'iso2' => 'SO', 'iso3' => 'SOM', 'iso_numerico' => '706'],
            ['nombre' => 'Sri Lanka',                              'nombre_ingles' => 'Sri Lanka',                                'iso2' => 'LK', 'iso3' => 'LKA', 'iso_numerico' => '144'],
            ['nombre' => 'Suazilandia',                            'nombre_ingles' => 'Eswatini',                                 'iso2' => 'SZ', 'iso3' => 'SWZ', 'iso_numerico' => '748'],
            ['nombre' => 'Sudáfrica',                              'nombre_ingles' => 'South Africa',                             'iso2' => 'ZA', 'iso3' => 'ZAF', 'iso_numerico' => '710'],
            ['nombre' => 'Sudán',                                  'nombre_ingles' => 'Sudan',                                    'iso2' => 'SD', 'iso3' => 'SDN', 'iso_numerico' => '729'],
            ['nombre' => 'Sudán del Sur',                          'nombre_ingles' => 'South Sudan',                              'iso2' => 'SS', 'iso3' => 'SSD', 'iso_numerico' => '728'],
            ['nombre' => 'Suecia',                                 'nombre_ingles' => 'Sweden',                                   'iso2' => 'SE', 'iso3' => 'SWE', 'iso_numerico' => '752'],
            ['nombre' => 'Suiza',                                  'nombre_ingles' => 'Switzerland',                              'iso2' => 'CH', 'iso3' => 'CHE', 'iso_numerico' => '756'],
            ['nombre' => 'Surinam',                                'nombre_ingles' => 'Suriname',                                 'iso2' => 'SR', 'iso3' => 'SUR', 'iso_numerico' => '740'],
            ['nombre' => 'Tailandia',                              'nombre_ingles' => 'Thailand',                                 'iso2' => 'TH', 'iso3' => 'THA', 'iso_numerico' => '764'],
            ['nombre' => 'Tanzania',                               'nombre_ingles' => 'Tanzania',                                 'iso2' => 'TZ', 'iso3' => 'TZA', 'iso_numerico' => '834'],
            ['nombre' => 'Tayikistán',                             'nombre_ingles' => 'Tajikistan',                               'iso2' => 'TJ', 'iso3' => 'TJK', 'iso_numerico' => '762'],
            ['nombre' => 'Timor Oriental',                         'nombre_ingles' => 'East Timor',                               'iso2' => 'TL', 'iso3' => 'TLS', 'iso_numerico' => '626'],
            ['nombre' => 'Togo',                                   'nombre_ingles' => 'Togo',                                     'iso2' => 'TG', 'iso3' => 'TGO', 'iso_numerico' => '768'],
            ['nombre' => 'Tonga',                                  'nombre_ingles' => 'Tonga',                                    'iso2' => 'TO', 'iso3' => 'TON', 'iso_numerico' => '776'],
            ['nombre' => 'Trinidad y Tobago',                      'nombre_ingles' => 'Trinidad and Tobago',                      'iso2' => 'TT', 'iso3' => 'TTO', 'iso_numerico' => '780'],
            ['nombre' => 'Túnez',                                  'nombre_ingles' => 'Tunisia',                                  'iso2' => 'TN', 'iso3' => 'TUN', 'iso_numerico' => '788'],
            ['nombre' => 'Turkmenistán',                           'nombre_ingles' => 'Turkmenistan',                             'iso2' => 'TM', 'iso3' => 'TKM', 'iso_numerico' => '795'],
            ['nombre' => 'Turquía',                                'nombre_ingles' => 'Turkey',                                   'iso2' => 'TR', 'iso3' => 'TUR', 'iso_numerico' => '792'],
            ['nombre' => 'Tuvalu',                                 'nombre_ingles' => 'Tuvalu',                                   'iso2' => 'TV', 'iso3' => 'TUV', 'iso_numerico' => '798'],
            ['nombre' => 'Ucrania',                                'nombre_ingles' => 'Ukraine',                                  'iso2' => 'UA', 'iso3' => 'UKR', 'iso_numerico' => '804'],
            ['nombre' => 'Uganda',                                 'nombre_ingles' => 'Uganda',                                   'iso2' => 'UG', 'iso3' => 'UGA', 'iso_numerico' => '800'],
            ['nombre' => 'Uruguay',                                'nombre_ingles' => 'Uruguay',                                  'iso2' => 'UY', 'iso3' => 'URY', 'iso_numerico' => '858'],
            ['nombre' => 'Uzbekistán',                             'nombre_ingles' => 'Uzbekistan',                               'iso2' => 'UZ', 'iso3' => 'UZB', 'iso_numerico' => '860'],
            ['nombre' => 'Vanuatu',                                'nombre_ingles' => 'Vanuatu',                                  'iso2' => 'VU', 'iso3' => 'VUT', 'iso_numerico' => '548'],
            ['nombre' => 'Venezuela',                              'nombre_ingles' => 'Venezuela',                                'iso2' => 'VE', 'iso3' => 'VEN', 'iso_numerico' => '862'],
            ['nombre' => 'Vietnam',                                'nombre_ingles' => 'Vietnam',                                  'iso2' => 'VN', 'iso3' => 'VNM', 'iso_numerico' => '704'],
            ['nombre' => 'Yemen',                                  'nombre_ingles' => 'Yemen',                                    'iso2' => 'YE', 'iso3' => 'YEM', 'iso_numerico' => '887'],
            ['nombre' => 'Yibuti',                                 'nombre_ingles' => 'Djibouti',                                 'iso2' => 'DJ', 'iso3' => 'DJI', 'iso_numerico' => '262'],
            ['nombre' => 'Zambia',                                 'nombre_ingles' => 'Zambia',                                   'iso2' => 'ZM', 'iso3' => 'ZMB', 'iso_numerico' => '894'],
            ['nombre' => 'Zimbabue',                               'nombre_ingles' => 'Zimbabwe',                                 'iso2' => 'ZW', 'iso3' => 'ZWE', 'iso_numerico' => '716'],
            // Additional ISO 3166-1 members and observer states
            ['nombre' => 'Samoa Americana',                        'nombre_ingles' => 'American Samoa',                           'iso2' => 'AS', 'iso3' => 'ASM', 'iso_numerico' => '016'],
            ['nombre' => 'Anguila',                                'nombre_ingles' => 'Anguilla',                                 'iso2' => 'AI', 'iso3' => 'AIA', 'iso_numerico' => '660'],
            ['nombre' => 'Antártida',                              'nombre_ingles' => 'Antarctica',                               'iso2' => 'AQ', 'iso3' => 'ATA', 'iso_numerico' => '010'],
            ['nombre' => 'Aruba',                                  'nombre_ingles' => 'Aruba',                                    'iso2' => 'AW', 'iso3' => 'ABW', 'iso_numerico' => '533'],
            ['nombre' => 'Islas Åland',                            'nombre_ingles' => 'Åland Islands',                            'iso2' => 'AX', 'iso3' => 'ALA', 'iso_numerico' => '248'],
            ['nombre' => 'Azerbaiyán',                             'nombre_ingles' => 'Azerbaijan',                               'iso2' => 'AZ', 'iso3' => 'AZE', 'iso_numerico' => '031'],
            ['nombre' => 'Bosnia y Herzegovina',                   'nombre_ingles' => 'Bosnia and Herzegovina',                   'iso2' => 'BA', 'iso3' => 'BIH', 'iso_numerico' => '070'],
            ['nombre' => 'Bermudas',                               'nombre_ingles' => 'Bermuda',                                  'iso2' => 'BM', 'iso3' => 'BMU', 'iso_numerico' => '060'],
            ['nombre' => 'Bonaire, San Eustaquio y Saba',          'nombre_ingles' => 'Bonaire, Sint Eustatius and Saba',         'iso2' => 'BQ', 'iso3' => 'BES', 'iso_numerico' => '535'],
            ['nombre' => 'Territorio Británico del Océano Índico', 'nombre_ingles' => 'British Indian Ocean Territory',           'iso2' => 'IO', 'iso3' => 'IOT', 'iso_numerico' => '086'],
            ['nombre' => 'Islas Vírgenes Británicas',              'nombre_ingles' => 'British Virgin Islands',                   'iso2' => 'VG', 'iso3' => 'VGB', 'iso_numerico' => '092'],
            ['nombre' => 'Islas Caimán',                           'nombre_ingles' => 'Cayman Islands',                           'iso2' => 'KY', 'iso3' => 'CYM', 'iso_numerico' => '136'],
            ['nombre' => 'Islas Cocos',                            'nombre_ingles' => 'Cocos (Keeling) Islands',                  'iso2' => 'CC', 'iso3' => 'CCK', 'iso_numerico' => '166'],
            ['nombre' => 'Isla de Man',                            'nombre_ingles' => 'Isle of Man',                              'iso2' => 'IM', 'iso3' => 'IMN', 'iso_numerico' => '833'],
            ['nombre' => 'Isla Christmas',                         'nombre_ingles' => 'Christmas Island',                         'iso2' => 'CX', 'iso3' => 'CXR', 'iso_numerico' => '162'],
            ['nombre' => 'Curazao',                                'nombre_ingles' => 'Curaçao',                                  'iso2' => 'CW', 'iso3' => 'CUW', 'iso_numerico' => '531'],
            ['nombre' => 'Yibuti',                                 'nombre_ingles' => 'Djibouti',                                 'iso2' => 'DJ', 'iso3' => 'DJI', 'iso_numerico' => '262'],
            ['nombre' => 'Ceuta y Melilla',                        'nombre_ingles' => 'Ceuta and Melilla',                        'iso2' => 'EA', 'iso3' => null,    'iso_numerico' => null],
            ['nombre' => 'Sahara Occidental',                      'nombre_ingles' => 'Western Sahara',                           'iso2' => 'EH', 'iso3' => 'ESH', 'iso_numerico' => '732'],
            ['nombre' => 'Islas Feroe',                            'nombre_ingles' => 'Faroe Islands',                            'iso2' => 'FO', 'iso3' => 'FRO', 'iso_numerico' => '234'],
            ['nombre' => 'Islas Malvinas',                         'nombre_ingles' => 'Falkland Islands',                         'iso2' => 'FK', 'iso3' => 'FLK', 'iso_numerico' => '238'],
            ['nombre' => 'Micronesia',                             'nombre_ingles' => 'Micronesia',                               'iso2' => 'FM', 'iso3' => 'FSM', 'iso_numerico' => '583'],
            ['nombre' => 'Guayana Francesa',                       'nombre_ingles' => 'French Guiana',                            'iso2' => 'GF', 'iso3' => 'GUF', 'iso_numerico' => '254'],
            ['nombre' => 'Groenlandia',                            'nombre_ingles' => 'Greenland',                                'iso2' => 'GL', 'iso3' => 'GRL', 'iso_numerico' => '304'],
            ['nombre' => 'Guadalupe',                              'nombre_ingles' => 'Guadeloupe',                               'iso2' => 'GP', 'iso3' => 'GLP', 'iso_numerico' => '312'],
            ['nombre' => 'Guam',                                   'nombre_ingles' => 'Guam',                                     'iso2' => 'GU', 'iso3' => 'GUM', 'iso_numerico' => '316'],
            ['nombre' => 'Guernesey',                              'nombre_ingles' => 'Guernsey',                                 'iso2' => 'GG', 'iso3' => 'GGY', 'iso_numerico' => '831'],
            ['nombre' => 'Heard e Islas McDonald',                 'nombre_ingles' => 'Heard Island and McDonald Islands',        'iso2' => 'HM', 'iso3' => 'HMD', 'iso_numerico' => '334'],
            ['nombre' => 'Hong Kong',                              'nombre_ingles' => 'Hong Kong',                                'iso2' => 'HK', 'iso3' => 'HKG', 'iso_numerico' => '344'],
            ['nombre' => 'Jersey',                                 'nombre_ingles' => 'Jersey',                                   'iso2' => 'JE', 'iso3' => 'JEY', 'iso_numerico' => '832'],
            ['nombre' => 'Kosovo',                                 'nombre_ingles' => 'Kosovo',                                   'iso2' => 'XK', 'iso3' => 'XKX', 'iso_numerico' => null],
            ['nombre' => 'Macao',                                  'nombre_ingles' => 'Macao',                                    'iso2' => 'MO', 'iso3' => 'MAC', 'iso_numerico' => '446'],
            ['nombre' => 'Macedonia del Norte',                    'nombre_ingles' => 'North Macedonia',                          'iso2' => 'MK', 'iso3' => 'MKD', 'iso_numerico' => '807'],
            ['nombre' => 'Martinica',                              'nombre_ingles' => 'Martinique',                               'iso2' => 'MQ', 'iso3' => 'MTQ', 'iso_numerico' => '474'],
            ['nombre' => 'Mayotte',                                'nombre_ingles' => 'Mayotte',                                  'iso2' => 'YT', 'iso3' => 'MYT', 'iso_numerico' => '175'],
            ['nombre' => 'Montserrat',                             'nombre_ingles' => 'Montserrat',                               'iso2' => 'MS', 'iso3' => 'MSR', 'iso_numerico' => '500'],
            ['nombre' => 'Nueva Caledonia',                        'nombre_ingles' => 'New Caledonia',                            'iso2' => 'NC', 'iso3' => 'NCL', 'iso_numerico' => '540'],
            ['nombre' => 'Isla Norfolk',                           'nombre_ingles' => 'Norfolk Island',                           'iso2' => 'NF', 'iso3' => 'NFK', 'iso_numerico' => '574'],
            ['nombre' => 'Islas Marianas del Norte',               'nombre_ingles' => 'Northern Mariana Islands',                 'iso2' => 'MP', 'iso3' => 'MNP', 'iso_numerico' => '580'],
            ['nombre' => 'Niue',                                   'nombre_ingles' => 'Niue',                                     'iso2' => 'NU', 'iso3' => 'NIU', 'iso_numerico' => '570'],
            ['nombre' => 'Polinesia Francesa',                     'nombre_ingles' => 'French Polynesia',                         'iso2' => 'PF', 'iso3' => 'PYF', 'iso_numerico' => '258'],
            ['nombre' => 'Puerto Rico',                            'nombre_ingles' => 'Puerto Rico',                              'iso2' => 'PR', 'iso3' => 'PRI', 'iso_numerico' => '630'],
            ['nombre' => 'Territorios Australes Franceses',        'nombre_ingles' => 'French Southern Territories',              'iso2' => 'TF', 'iso3' => 'ATF', 'iso_numerico' => '260'],
            ['nombre' => 'Reunión',                                'nombre_ingles' => 'Réunion',                                  'iso2' => 'RE', 'iso3' => 'REU', 'iso_numerico' => '638'],
            ['nombre' => 'Santa Helena',                           'nombre_ingles' => 'Saint Helena',                             'iso2' => 'SH', 'iso3' => 'SHN', 'iso_numerico' => '654'],
            ['nombre' => 'San Pedro y Miquelón',                   'nombre_ingles' => 'Saint Pierre and Miquelon',                'iso2' => 'PM', 'iso3' => 'SPM', 'iso_numerico' => '666'],
            ['nombre' => 'San Bartolomé',                          'nombre_ingles' => 'Saint Barthélemy',                         'iso2' => 'BL', 'iso3' => 'BLM', 'iso_numerico' => '652'],
            ['nombre' => 'San Martín (parte francesa)',            'nombre_ingles' => 'Saint Martin (French part)',                'iso2' => 'MF', 'iso3' => 'MAF', 'iso_numerico' => '663'],
            ['nombre' => 'Sint Maarten (parte neerlandesa)',       'nombre_ingles' => 'Sint Maarten (Dutch part)',                 'iso2' => 'SX', 'iso3' => 'SXM', 'iso_numerico' => '534'],
            ['nombre' => 'Islas Svalbard y Jan Mayen',             'nombre_ingles' => 'Svalbard and Jan Mayen',                   'iso2' => 'SJ', 'iso3' => 'SJM', 'iso_numerico' => '744'],
            ['nombre' => 'Islas Turcas y Caicos',                  'nombre_ingles' => 'Turks and Caicos Islands',                 'iso2' => 'TC', 'iso3' => 'TCA', 'iso_numerico' => '796'],
            ['nombre' => 'Taiwán',                                 'nombre_ingles' => 'Taiwan',                                   'iso2' => 'TW', 'iso3' => 'TWN', 'iso_numerico' => '158'],
            ['nombre' => 'Islas Vírgenes de los Estados Unidos',   'nombre_ingles' => 'United States Virgin Islands',             'iso2' => 'VI', 'iso3' => 'VIR', 'iso_numerico' => '850'],
            ['nombre' => 'Wallis y Futuna',                        'nombre_ingles' => 'Wallis and Futuna',                        'iso2' => 'WF', 'iso3' => 'WLF', 'iso_numerico' => '876'],
            ['nombre' => 'Islas Pitcairn',                         'nombre_ingles' => 'Pitcairn Islands',                         'iso2' => 'PN', 'iso3' => 'PCN', 'iso_numerico' => '612'],
            ['nombre' => 'Islas Ultramarinas Menores de EE. UU.', 'nombre_ingles' => 'United States Minor Outlying Islands',     'iso2' => 'UM', 'iso3' => 'UMI', 'iso_numerico' => '581'],
            ['nombre' => 'Georgia del Sur e Islas Sandwich del Sur','nombre_ingles' => 'South Georgia and the South Sandwich Islands','iso2' => 'GS', 'iso3' => 'SGS', 'iso_numerico' => '239'],
            ['nombre' => 'Tokelau',                                'nombre_ingles' => 'Tokelau',                                  'iso2' => 'TK', 'iso3' => 'TKL', 'iso_numerico' => '772'],
            ['nombre' => 'Cook Islands',                           'nombre_ingles' => 'Cook Islands',                             'iso2' => 'CK', 'iso3' => 'COK', 'iso_numerico' => '184'],
            ['nombre' => 'Isla Bouvet',                            'nombre_ingles' => 'Bouvet Island',                            'iso2' => 'BV', 'iso3' => 'BVT', 'iso_numerico' => '074'],
            ['nombre' => 'Territorios Australes Británicos',       'nombre_ingles' => 'British Antarctic Territory',              'iso2' => '',   'iso3' => null,    'iso_numerico' => null],
        ];

        foreach ($paises as $pais) {
            if (empty($pais['iso2'])) {
                continue;
            }
            Pais::firstOrCreate(
                ['iso2' => $pais['iso2']],
                [
                    'nombre'        => $pais['nombre'],
                    'nombre_ingles' => $pais['nombre_ingles'],
                    'iso3'          => $pais['iso3'],
                    'iso_numerico'  => $pais['iso_numerico'],
                ]
            );
        }
    }

    private function seedEstadosArgentina(): void
    {
        $argentina = Pais::where('iso2', 'AR')->first();
        if (!$argentina) {
            return;
        }

        $provincias = [
            'Buenos Aires',
            'Catamarca',
            'Chaco',
            'Chubut',
            'Ciudad Autónoma de Buenos Aires',
            'Córdoba',
            'Corrientes',
            'Entre Ríos',
            'Formosa',
            'Jujuy',
            'La Pampa',
            'La Rioja',
            'Mendoza',
            'Misiones',
            'Neuquén',
            'Río Negro',
            'Salta',
            'San Juan',
            'San Luis',
            'Santa Cruz',
            'Santa Fe',
            'Santiago del Estero',
            'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
            'Tucumán',
        ];

        foreach ($provincias as $nombre) {
            Estado::firstOrCreate(
                ['nombre' => $nombre, 'id_pais' => $argentina->id],
                ['id_pais' => $argentina->id]
            );
        }
    }

    private function seedCiudadesArgentina(): void
    {
        $argentina = Pais::where('iso2', 'AR')->first();
        if (!$argentina) {
            return;
        }

        $departamentosPorProvincia = $this->getDepartamentos();

        foreach ($departamentosPorProvincia as $nombreProvincia => $departamentos) {
            $estado = Estado::where('nombre', $nombreProvincia)
                ->where('id_pais', $argentina->id)
                ->first();

            if (!$estado) {
                continue;
            }

            foreach ($departamentos as $departamento) {
                Ciudad::firstOrCreate(
                    ['nombre' => $departamento, 'id_estado' => $estado->id],
                    ['id_estado' => $estado->id]
                );
            }
        }
    }

    private function getDepartamentos(): array
    {
        return [
            // ----------------------------------------------------------------
            // SAN JUAN — 19 departamentos
            // ----------------------------------------------------------------
            'San Juan' => [
                'Albardón',
                'Angaco',
                'Calingasta',
                'Capital',
                'Caucete',
                'Chimbas',
                'Iglesia',
                'Jáchal',
                'Nueve de Julio',
                'Pocito',
                'Rawson',
                'Rivadavia',
                'San Martín',
                'Santa Lucía',
                'Sarmiento',
                'Ullum',
                'Valle Fértil',
                'Veinticinco de Mayo',
                'Zonda',
            ],

            // ----------------------------------------------------------------
            // BUENOS AIRES — partidos seleccionados (GBA + principales)
            // ----------------------------------------------------------------
            'Buenos Aires' => [
                'Adolfo Alsina',
                'Adolfo Gonzales Chaves',
                'Alberti',
                'Almirante Brown',
                'Avellaneda',
                'Ayacucho',
                'Azul',
                'Bahía Blanca',
                'Balcarce',
                'Baradero',
                'Benito Juárez',
                'Berazategui',
                'Berisso',
                'Bolívar',
                'Bragado',
                'Brandsen',
                'Campana',
                'Cañuelas',
                'Capitán Sarmiento',
                'Carlos Casares',
                'Carlos Tejedor',
                'Carmen de Areco',
                'Castelli',
                'Chacabuco',
                'Chascomús',
                'Chivilcoy',
                'Colón',
                'Coronel de Marina Leonardo Rosales',
                'Coronel Dorrego',
                'Coronel Pringles',
                'Coronel Suárez',
                'Daireaux',
                'Dolores',
                'Ensenada',
                'Escobar',
                'Esteban Echeverría',
                'Exaltación de la Cruz',
                'Ezeiza',
                'Florencio Varela',
                'Florentino Ameghino',
                'General Alvarado',
                'General Alvear',
                'General Arenales',
                'General Belgrano',
                'General Guido',
                'General Juan Madariaga',
                'General La Madrid',
                'General Las Heras',
                'General Lavalle',
                'General Paz',
                'General Pinto',
                'General Pueyrredón',
                'General Rodríguez',
                'General San Martín',
                'General Viamonte',
                'General Villegas',
                'Guaminí',
                'Hipólito Yrigoyen',
                'Hurlingham',
                'Ituzaingó',
                'José C. Paz',
                'Junín',
                'La Costa',
                'La Matanza',
                'La Plata',
                'Lanús',
                'Laprida',
                'Las Flores',
                'Leandro N. Alem',
                'Lincoln',
                'Lomas de Zamora',
                'Luján',
                'Magdalena',
                'Maipú',
                'Malvinas Argentinas',
                'Mar Chiquita',
                'Marcos Paz',
                'Mercedes',
                'Merlo',
                'Monte',
                'Monte Hermoso',
                'Moreno',
                'Morón',
                'Navarro',
                'Necochea',
                'Nueve de Julio',
                'Olavarría',
                'Patagones',
                'Pehuajó',
                'Pellegrini',
                'Pergamino',
                'Pila',
                'Pilar',
                'Pinamar',
                'Presidente Perón',
                'Puán',
                'Punta Indio',
                'Quilmes',
                'Ramallo',
                'Rauch',
                'Rivadavia',
                'Rojas',
                'Roque Pérez',
                'Saavedra',
                'Saladillo',
                'Salliqueló',
                'Salto',
                'San Andrés de Giles',
                'San Antonio de Areco',
                'San Cayetano',
                'San Fernando',
                'San Isidro',
                'San Miguel',
                'San Nicolás',
                'San Pedro',
                'San Vicente',
                'Suipacha',
                'Tandil',
                'Tapalqué',
                'Tigre',
                'Tordillo',
                'Tornquist',
                'Trenque Lauquen',
                'Tres Arroyos',
                'Tres de Febrero',
                'Tres Lomas',
                'Vicente López',
                'Veinticinco de Mayo',
                'Villa Gesell',
                'Villarino',
                'Zárate',
            ],

            // ----------------------------------------------------------------
            // CIUDAD AUTÓNOMA DE BUENOS AIRES — comunas
            // ----------------------------------------------------------------
            'Ciudad Autónoma de Buenos Aires' => [
                'Comuna 1',
                'Comuna 2',
                'Comuna 3',
                'Comuna 4',
                'Comuna 5',
                'Comuna 6',
                'Comuna 7',
                'Comuna 8',
                'Comuna 9',
                'Comuna 10',
                'Comuna 11',
                'Comuna 12',
                'Comuna 13',
                'Comuna 14',
                'Comuna 15',
            ],

            // ----------------------------------------------------------------
            // CATAMARCA — 16 departamentos
            // ----------------------------------------------------------------
            'Catamarca' => [
                'Ambato',
                'Ancasti',
                'Andalgalá',
                'Antofagasta de la Sierra',
                'Belén',
                'Capayán',
                'Capital',
                'El Alto',
                'Fray Mamerto Esquiú',
                'La Paz',
                'Paclín',
                'Pomán',
                'Santa María',
                'Santa Rosa',
                'Tinogasta',
                'Valle Viejo',
            ],

            // ----------------------------------------------------------------
            // CHACO — 25 departamentos
            // ----------------------------------------------------------------
            'Chaco' => [
                'Almirante Brown',
                'Bermejo',
                'Chacabuco',
                'Comandante Fernández',
                'Doce de Octubre',
                'Dos de Abril',
                'Fray Justo Santa María de Oro',
                'General Belgrano',
                'General Donovan',
                'General Güemes',
                'Independencia',
                'Libertad',
                'Libertador General San Martín',
                'Maipú',
                'Mayor Luis Jorge Fontana',
                'Nueve de Julio',
                'O\'Higgins',
                'Presidencia de la Plaza',
                'Primero de Mayo',
                'Quitilipi',
                'San Fernando',
                'San Lorenzo',
                'Sargento Cabral',
                'Tapenagá',
                'Veinticinco de Mayo',
            ],

            // ----------------------------------------------------------------
            // CHUBUT — 15 departamentos
            // ----------------------------------------------------------------
            'Chubut' => [
                'Biedma',
                'Cushamen',
                'Escalante',
                'Florentino Ameghino',
                'Futaleufú',
                'Gastre',
                'Languiñeo',
                'Mártires',
                'Paso de Indios',
                'Rawson',
                'Río Senguer',
                'Sarmiento',
                'Tehuelches',
                'Telsen',
                'Río Senguer',
            ],

            // ----------------------------------------------------------------
            // CÓRDOBA — 26 departamentos
            // ----------------------------------------------------------------
            'Córdoba' => [
                'Calamuchita',
                'Capital',
                'Colón',
                'Cruz del Eje',
                'General Roca',
                'General San Martín',
                'Ischilín',
                'Juárez Celman',
                'Marcos Juárez',
                'Minas',
                'Pocho',
                'Presidente Roque Sáenz Peña',
                'Punilla',
                'Río Cuarto',
                'Río Primero',
                'Río Seco',
                'Río Segundo',
                'San Alberto',
                'San Javier',
                'San Justo',
                'Santa María',
                'Sobremonte',
                'Tercero Arriba',
                'Totoral',
                'Tulumba',
                'Unión',
            ],

            // ----------------------------------------------------------------
            // CORRIENTES — 25 departamentos
            // ----------------------------------------------------------------
            'Corrientes' => [
                'Bella Vista',
                'Berón de Astrada',
                'Capital',
                'Concepción',
                'Curuzú Cuatiá',
                'Empedrado',
                'Esquina',
                'General Álvarez',
                'General Paz',
                'Goya',
                'Itatí',
                'Ituzaingó',
                'Lavalle',
                'Mburucuyá',
                'Mercedes',
                'Monte Caseros',
                'Paso de los Libres',
                'Saladas',
                'San Cosme',
                'San Luis del Palmar',
                'San Martín',
                'San Miguel',
                'San Roque',
                'Santo Tomé',
                'Sauce',
            ],

            // ----------------------------------------------------------------
            // ENTRE RÍOS — 17 departamentos
            // ----------------------------------------------------------------
            'Entre Ríos' => [
                'Colón',
                'Concordia',
                'Diamante',
                'Federación',
                'Federal',
                'Feliciano',
                'Gualeguay',
                'Gualeguaychú',
                'Islas del Ibicuy',
                'La Paz',
                'Nogoyá',
                'Paraná',
                'San Salvador',
                'Tala',
                'Uruguay',
                'Victoria',
                'Villaguay',
            ],

            // ----------------------------------------------------------------
            // FORMOSA — 9 departamentos
            // ----------------------------------------------------------------
            'Formosa' => [
                'Bermejo',
                'Formosa',
                'Laishi',
                'Matacos',
                'Patiño',
                'Pilcomayo',
                'Pilagás',
                'Pirané',
                'Ramón Lista',
            ],

            // ----------------------------------------------------------------
            // JUJUY — 16 departamentos
            // ----------------------------------------------------------------
            'Jujuy' => [
                'Capital',
                'Cochinoca',
                'El Carmen',
                'Humahuaca',
                'Ledesma',
                'Palpalá',
                'Rinconada',
                'San Antonio',
                'San Pedro',
                'Santa Bárbara',
                'Santa Catalina',
                'Susques',
                'Tilcara',
                'Tumbaya',
                'Valle Grande',
                'Yavi',
            ],

            // ----------------------------------------------------------------
            // LA PAMPA — 22 departamentos
            // ----------------------------------------------------------------
            'La Pampa' => [
                'Atreucó',
                'Caleu Caleu',
                'Capital',
                'Catriló',
                'Chalileo',
                'Chapaleufú',
                'Chical Co',
                'Conhelo',
                'Curacó',
                'General Acha',
                'Guatraché',
                'Hucal',
                'Lihuel Calel',
                'Limay Mahuida',
                'Loventué',
                'Maracó',
                'Puelén',
                'Quehué',
                'Rancul',
                'Realicó',
                'Toay',
                'Utracán',
            ],

            // ----------------------------------------------------------------
            // LA RIOJA — 18 departamentos
            // ----------------------------------------------------------------
            'La Rioja' => [
                'Arauco',
                'Castro Barros',
                'Coronel Felipe Varela',
                'Famatina',
                'General Ángel Vicente Peñaloza',
                'General Belgrano',
                'General Juan Facundo Quiroga',
                'General Lamadrid',
                'General San Martín',
                'Independencia',
                'Municipio de la Capital',
                'Rosario Vera Peñaloza',
                'San Blas de los Sauces',
                'Sanagasta',
                'Vinchina',
                'Ángel Vicente Peñaloza',
                'Capital',
                'Chilecito',
            ],

            // ----------------------------------------------------------------
            // MENDOZA — 18 departamentos
            // ----------------------------------------------------------------
            'Mendoza' => [
                'Capital',
                'General Alvear',
                'Godoy Cruz',
                'Guaymallén',
                'Junín',
                'La Paz',
                'Las Heras',
                'Lavalle',
                'Luján de Cuyo',
                'Maipú',
                'Malargüe',
                'Rivadavia',
                'San Carlos',
                'San Martín',
                'San Rafael',
                'Santa Rosa',
                'Tunuyán',
                'Tupungato',
            ],

            // ----------------------------------------------------------------
            // MISIONES — 17 departamentos
            // ----------------------------------------------------------------
            'Misiones' => [
                'Apóstoles',
                'Cainguás',
                'Candelaria',
                'Capital',
                'Concepción',
                'El Dorado',
                'General Manuel Belgrano',
                'Guaraní',
                'Iguazú',
                'Leandro N. Alem',
                'Libertador General San Martín',
                'Montecarlo',
                'Oberá',
                'San Ignacio',
                'San Javier',
                'San Pedro',
                'Veinticinco de Mayo',
            ],

            // ----------------------------------------------------------------
            // NEUQUÉN — 16 departamentos
            // ----------------------------------------------------------------
            'Neuquén' => [
                'Aluminé',
                'Añelo',
                'Catán Lil',
                'Chos Malal',
                'Collón Curá',
                'Confluencia',
                'Huiliches',
                'Lácar',
                'Loncopué',
                'Los Lagos',
                'Minas',
                'Norquín',
                'Pehuenches',
                'Picún Leufú',
                'Picunches',
                'Zapala',
            ],

            // ----------------------------------------------------------------
            // RÍO NEGRO — 13 departamentos
            // ----------------------------------------------------------------
            'Río Negro' => [
                'Adolfo Alsina',
                'Avellaneda',
                'Bariloche',
                'Conesa',
                'El Cuy',
                'General Roca',
                'Ñorquincó',
                'Nueve de Julio',
                'Pichi Mahuida',
                'Pilcaniyeu',
                'San Antonio',
                'Valcheta',
                'Veinticinco de Mayo',
            ],

            // ----------------------------------------------------------------
            // SALTA — 23 departamentos
            // ----------------------------------------------------------------
            'Salta' => [
                'Anta',
                'Cachi',
                'Cafayate',
                'Capital',
                'Cerrillos',
                'Chicoana',
                'General Güemes',
                'General José de San Martín',
                'Guachipas',
                'Iruya',
                'La Caldera',
                'La Candelaria',
                'La Poma',
                'La Viña',
                'Los Andes',
                'Metán',
                'Molinos',
                'Orán',
                'Rivadavia',
                'Rosario de la Frontera',
                'Rosario de Lerma',
                'San Carlos',
                'Santa Victoria',
            ],

            // ----------------------------------------------------------------
            // SAN LUIS — 9 departamentos
            // ----------------------------------------------------------------
            'San Luis' => [
                'Ayacucho',
                'Belgrano',
                'Chacabuco',
                'Coronel Pringles',
                'General Pedernera',
                'Gobernador Dupuy',
                'Junín',
                'La Capital',
                'Libertador General San Martín',
            ],

            // ----------------------------------------------------------------
            // SANTA CRUZ — 7 departamentos
            // ----------------------------------------------------------------
            'Santa Cruz' => [
                'Corpen Aike',
                'Deseado',
                'Güer Aike',
                'Lago Argentino',
                'Lago Buenos Aires',
                'Magallanes',
                'Río Chico',
            ],

            // ----------------------------------------------------------------
            // SANTA FE — 19 departamentos
            // ----------------------------------------------------------------
            'Santa Fe' => [
                'Belgrano',
                'Caseros',
                'Castellanos',
                'Constitución',
                'Garay',
                'General López',
                'General Obligado',
                'Iriondo',
                'La Capital',
                'Las Colonias',
                'Nueve de Julio',
                'Rosario',
                'San Cristóbal',
                'San Javier',
                'San Jerónimo',
                'San Justo',
                'San Lorenzo',
                'San Martín',
                'Vera',
            ],

            // ----------------------------------------------------------------
            // SANTIAGO DEL ESTERO — 27 departamentos
            // ----------------------------------------------------------------
            'Santiago del Estero' => [
                'Aguirre',
                'Alberdi',
                'Atamisqui',
                'Avellaneda',
                'Banda',
                'Belgrano',
                'Capital',
                'Choya',
                'Copo',
                'Figueroa',
                'General Taboada',
                'Guasayán',
                'Jiménez',
                'Juan Felipe Ibarra',
                'Loreto',
                'Mitre',
                'Moreno',
                'Ojo de Agua',
                'Pellegrini',
                'Quebrachos',
                'Río Hondo',
                'Rivadavia',
                'Robles',
                'Salavina',
                'San Martín',
                'Silípica',
                'Sarmiento',
            ],

            // ----------------------------------------------------------------
            // TIERRA DEL FUEGO — 2 departamentos
            // ----------------------------------------------------------------
            'Tierra del Fuego, Antártida e Islas del Atlántico Sur' => [
                'Ushuaia',
                'Río Grande',
            ],

            // ----------------------------------------------------------------
            // TUCUMÁN — 17 departamentos
            // ----------------------------------------------------------------
            'Tucumán' => [
                'Burruyacú',
                'Capital',
                'Chicligasta',
                'Cruz Alta',
                'Famaillá',
                'Graneros',
                'Juan Bautista Alberdi',
                'La Cocha',
                'Leales',
                'Lules',
                'Monteros',
                'Río Chico',
                'Simoca',
                'Tafí del Valle',
                'Tafí Viejo',
                'Trancas',
                'Yerba Buena',
            ],
        ];
    }
}
